from enum import Enum


class UserRole(str, Enum):
    LEARNER = "LEARNER"
    EDUCATOR = "EDUCATOR"
    CONTENT_CREATOR = "CONTENT_CREATOR"
    ADMIN = "ADMIN"

class ActivityType(str, Enum):
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    PROFILE_UPDATED = "PROFILE_UPDATED"

    VIDEO_UPLOADED = "VIDEO_UPLOADED"
    VIDEO_DELETED = "VIDEO_DELETED"

    TRANSCRIPT_GENERATED = "TRANSCRIPT_GENERATED"
    TRANSCRIPT_VIEWED = "TRANSCRIPT_VIEWED"
    TRANSCRIPT_DOWNLOADED = "TRANSCRIPT_DOWNLOADED"
    TRANSCRIPT_SEGMENTS_VIEWED = "TRANSCRIPT_SEGMENTS_VIEWED"

    SUMMARY_GENERATED = "SUMMARY_GENERATED"
    SUMMARY_VIEWED = "SUMMARY_VIEWED"
    SUMMARY_DOWNLOADED = "SUMMARY_DOWNLOADED"

    KEY_MOMENTS_DETECTED = "KEY_MOMENTS_DETECTED"
    KEY_MOMENTS_VIEWED = "key_moments_viewed"

    KEYWORDS_GENERATED = "keywords_generated"
    KEYWORDS_VIEWED = "keywords_viewed"

    HIGHLIGHT_REPORT_GENERATED = "highlight_report_generated"
    HIGHLIGHT_REPORT_VIEWED = "highlight_report_viewed"

    BOOKMARK_ADDED = "BOOKMARK_ADDED"
    BOOKMARK_REMOVED = "BOOKMARK_REMOVED"

class VideoStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class SummaryType(str, Enum):
    SHORT = "SHORT"
    DETAILED = "DETAILED"
    EDUCATIONAL = "EDUCATIONAL"

