from enum import Enum


class UserRole(str, Enum):
    LEARNER = "LEARNER"
    EDUCATOR = "EDUCATOR"
    CONTENT_CREATOR = "CONTENT_CREATOR"
    ADMIN = "ADMIN"

class ActivityType(str, Enum):
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    PROFILE_UPDATED = "PROFILE_UPDATED"
    VIDEO_UPLOADED = "VIDEO_UPLOADED"
    VIDEO_DELETED = "VIDEO_DELETED"

    TRANSCRIPT_GENERATED = "TRANSCRIPT_GENERATED"
    SUMMARY_GENERATED = "SUMMARY_GENERATED"
    KEY_MOMENTS_DETECTED = "KEY_MOMENTS_DETECTED"

    BOOKMARK_ADDED = "BOOKMARK_ADDED"
    SUMMARY_DOWNLOADED = "SUMMARY_DOWNLOADED"


class VideoStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class SummaryType(str, Enum):
    SHORT = "SHORT"
    DETAILED = "DETAILED"
    EDUCATIONAL = "EDUCATIONAL"

