import React, { useEffect, useState, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  FiArrowLeft, FiFileText, FiList, FiZap,
  FiDownload, FiShare2, FiCopy, FiCheck,
  FiAlertCircle, FiBookOpen,
} from 'react-icons/fi';
import { jsPDF } from 'jspdf';
import videoService from '../services/videoService.js';


const Notes = () => {
  const { videoId } = useParams();
  const navigate = useNavigate();

  const [video, setVideo] = useState(null);
  const [transcript, setTranscript] = useState(null);
  const [summary, setSummary] = useState(null);
  const [keyMoments, setKeyMoments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);
  const [exportingTxt, setExportingTxt] = useState(false);

  useEffect(() => {
    fetchNotesData();
  }, [videoId]);

  const fetchNotesData = async () => {
    try {
      setLoading(true);
      setError('');

      const [videoData, transcriptData, summaryResult, momentsData] =
        await Promise.allSettled([
          videoService.getVideo(videoId),
          videoService.getTranscript(videoId),
          videoService.getSummary(videoId),
          videoService.getKeyMoments(videoId),
        ]);

      if (videoData.status === 'fulfilled') {
        setVideo(videoData.value);
      }
      if (transcriptData.status === 'fulfilled') {
        setTranscript(transcriptData.value);
      }
      if (summaryResult.status === 'fulfilled') {
        setSummary(summaryResult.value);
      }
      if (momentsData.status === 'fulfilled' && Array.isArray(momentsData.value)) {
        setKeyMoments(momentsData.value);
      }
    } catch (err) {
      setError('Failed to load notes data');
    } finally {
      setLoading(false);
    }
  };

  const formatTimestamp = (seconds) => {
    if (seconds === null || seconds === undefined) return 'N/A';
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // Build the full notes text content
  const getNotesText = useCallback(() => {
    const lines = [];
    const videoTitle = video?.title || 'Untitled Video';
    const divider = '='.repeat(60);

    lines.push(divider);
    lines.push(`VIDEO NOTES: ${videoTitle}`);
    lines.push(divider);
    lines.push('');

    // Summary
    if (summary) {
      lines.push('📝 SUMMARY');
      lines.push('-'.repeat(40));
      if (summary.short_summary) {
        lines.push('');
        lines.push('Short Summary:');
        lines.push(summary.short_summary);
      }
      if (summary.detailed_summary) {
        lines.push('');
        lines.push('Detailed Summary:');
        lines.push(summary.detailed_summary);
      }
      lines.push('');
    }

    // Transcript
    if (transcript?.transcript) {
      lines.push('🎙 TRANSCRIPT');
      lines.push('-'.repeat(40));
      lines.push('');
      lines.push(transcript.transcript);
      lines.push('');
    }

    // Key Moments
    if (keyMoments.length > 0) {
      lines.push('⏱ KEY MOMENTS');
      lines.push('-'.repeat(40));
      lines.push('');
      keyMoments.forEach((moment, index) => {
        const timestamp = formatTimestamp(moment.start_time);
        lines.push(`${timestamp} - ${moment.title}`);
        if (moment.description) {
          lines.push(`  ${moment.description}`);
        }
        lines.push('');
      });
    }

    lines.push(divider);
    lines.push(`Generated by ClipMind AI`);
    lines.push(`Source: ${window.location.href}`);

    return lines.join('\n');
  }, [video, summary, transcript, keyMoments]);

  // Build HTML for PDF
  const getNotesHTML = useCallback(() => {
    const videoTitle = video?.title || 'Untitled Video';
    const parts = [];

    // Title
    parts.push(`<h1 style="font-size:24px;font-weight:bold;text-align:center;margin-bottom:5px;">Video Notes</h1>`);
    parts.push(`<h2 style="font-size:16px;text-align:center;color:#666;margin-bottom:20px;border-bottom:2px solid #333;padding-bottom:10px;">${videoTitle}</h2>`);

    // Summary
    if (summary) {
      parts.push(`<h3 style="font-size:18px;font-weight:bold;margin-top:20px;margin-bottom:10px;color:#1a73e8;">📝 Summary</h3>`);
      parts.push(`<hr style="border:1px solid #ddd;">`);
      if (summary.short_summary) {
        parts.push(`<h4 style="font-size:14px;font-weight:bold;margin-top:10px;margin-bottom:5px;">Short Summary</h4>`);
        parts.push(`<p style="font-size:12px;line-height:1.6;margin-bottom:10px;">${summary.short_summary}</p>`);
      }
      if (summary.detailed_summary) {
        parts.push(`<h4 style="font-size:14px;font-weight:bold;margin-top:10px;margin-bottom:5px;">Detailed Summary</h4>`);
        parts.push(`<p style="font-size:12px;line-height:1.6;margin-bottom:10px;">${summary.detailed_summary}</p>`);
      }
    }

    // Transcript
    if (transcript?.transcript) {
      parts.push(`<h3 style="font-size:18px;font-weight:bold;margin-top:20px;margin-bottom:10px;color:#1a73e8;">🎙 Transcript</h3>`);
      parts.push(`<hr style="border:1px solid #ddd;">`);
      parts.push(`<p style="font-size:11px;line-height:1.6;white-space:pre-wrap;margin-bottom:10px;">${transcript.transcript}</p>`);
    }

    // Key Moments
    if (keyMoments.length > 0) {
      parts.push(`<h3 style="font-size:18px;font-weight:bold;margin-top:20px;margin-bottom:10px;color:#1a73e8;">⏱ Key Moments</h3>`);
      parts.push(`<hr style="border:1px solid #ddd;">`);
      parts.push(`<table style="width:100%;border-collapse:collapse;font-size:12px;">`);
      parts.push(`<thead><tr style="background:#f0f0f0;"><th style="padding:8px;border:1px solid #ddd;text-align:left;">Time</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Title</th><th style="padding:8px;border:1px solid #ddd;text-align:left;">Description</th></tr></thead>`);
      parts.push(`<tbody>`);
      keyMoments.forEach((moment) => {
        const timestamp = formatTimestamp(moment.start_time);
        parts.push(`<tr><td style="padding:8px;border:1px solid #ddd;font-weight:bold;white-space:nowrap;">${timestamp}</td><td style="padding:8px;border:1px solid #ddd;">${moment.title}</td><td style="padding:8px;border:1px solid #ddd;">${moment.description || ''}</td></tr>`);
      });
      parts.push(`</tbody></table>`);
    }

    // Footer
    parts.push(`<p style="text-align:center;font-size:10px;color:#999;margin-top:30px;border-top:1px solid #ddd;padding-top:10px;">Generated by ClipMind AI</p>`);

    return parts.join('\n');
  }, [video, summary, transcript, keyMoments]);

  // Export as PDF
  const handleExportPDF = async () => {
    try {
      setExportingPdf(true);
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - 2 * margin;
      const videoTitle = video?.title || 'Untitled Video';
      let y = margin;

      // Helper to add text with word wrap
      const addText = (text, size, style, color, indent = 0) => {
        doc.setFontSize(size);
        if (style) doc.setFont(undefined, style);
        if (color) doc.setTextColor(color);
        const lines = doc.splitTextToSize(text, contentWidth - indent);
        lines.forEach((line) => {
          if (y + 7 > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
          }
          doc.text(line, margin + indent, y);
          y += 6;
        });
      };

      // Title
      doc.setFontSize(22);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(0, 0, 0);
      const titleLines = doc.splitTextToSize('Video Notes', contentWidth);
      doc.text(titleLines, margin, y);
      y += 8;

      // Video title
      doc.setFontSize(14);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(100, 100, 100);
      const videoTitleLines = doc.splitTextToSize(videoTitle, contentWidth);
      doc.text(videoTitleLines, margin, y);
      y += 10;

      // Divider
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      // Summary section
      if (summary) {
        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(26, 115, 232);
        doc.text('Summary', margin, y);
        y += 8;

        doc.setDrawColor(220, 220, 220);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;

        if (summary.short_summary) {
          doc.setFontSize(12);
          doc.setFont(undefined, 'bold');
          doc.setTextColor(50, 50, 50);
          doc.text('Short Summary', margin, y);
          y += 6;

          doc.setFontSize(11);
          doc.setFont(undefined, 'normal');
          doc.setTextColor(80, 80, 80);
          addText(summary.short_summary, 11, 'normal', 80);
          y += 4;
        }

        if (summary.detailed_summary) {
          if (y + 20 > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
          }

          doc.setFontSize(12);
          doc.setFont(undefined, 'bold');
          doc.setTextColor(50, 50, 50);
          doc.text('Detailed Summary', margin, y);
          y += 6;

          doc.setFontSize(11);
          doc.setFont(undefined, 'normal');
          doc.setTextColor(80, 80, 80);
          addText(summary.detailed_summary, 11, 'normal', 80);
          y += 4;
        }

        y += 6;
      }

      // Transcript section
      if (transcript?.transcript) {
        if (y + 20 > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }

        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(26, 115, 232);
        doc.text('Transcript', margin, y);
        y += 8;

        doc.setDrawColor(220, 220, 220);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;

        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(80, 80, 80);
        addText(transcript.transcript, 10, 'normal', 80);
        y += 6;
      }

      // Key Moments section
      if (keyMoments.length > 0) {
        if (y + 20 > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }

        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(26, 115, 232);
        doc.text('Key Moments', margin, y);
        y += 8;

        doc.setDrawColor(220, 220, 220);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;

        // Table header
        doc.setFontSize(11);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(50, 50, 50);
        doc.setFillColor(240, 240, 240);
        doc.rect(margin, y - 4, contentWidth, 8, 'F');
        doc.text('Time', margin + 2, y + 1);
        doc.text('Title', margin + 25, y + 1);
        doc.text('Description', margin + 80, y + 1);
        y += 10;

        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(80, 80, 80);

        keyMoments.forEach((moment) => {
          if (y + 10 > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
          }

          const timestamp = formatTimestamp(moment.start_time);
          doc.text(timestamp, margin + 2, y);

          const title = moment.title || '';
          const titleLines = doc.splitTextToSize(title, 50);
          doc.text(titleLines, margin + 25, y);

          const desc = moment.description || '';
          const descLines = doc.splitTextToSize(desc, contentWidth - 100);
          doc.text(descLines, margin + 80, y);

          // Calculate row height based on max lines
          const maxLines = Math.max(titleLines.length, descLines.length, 1);
          y += maxLines * 5 + 4;
        });

        y += 6;
      }

      // Footer
      if (y + 20 > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;
      doc.setFontSize(9);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by ClipMind AI', margin, y);

      // Save
      const fileName = `notes-${videoTitle.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}.pdf`;
      doc.save(fileName);
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setExportingPdf(false);
    }
  };

  // Export as TXT
  const handleExportTXT = () => {
    try {
      setExportingTxt(true);
      const text = getNotesText();
      const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const videoTitle = video?.title || 'Untitled Video';
      link.href = url;
      link.download = `notes-${videoTitle.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40)}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('TXT export failed:', err);
      alert('Failed to export TXT. Please try again.');
    } finally {
      setExportingTxt(false);
    }
  };

  // Copy all notes to clipboard
  const handleCopy = async () => {
    try {
      const text = getNotesText();
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (err) {
      // Fallback for older browsers
      try {
        const textarea = document.createElement('textarea');
        textarea.value = getNotesText();
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        setCopied(true);
        setTimeout(() => setCopied(false), 3000);
      } catch (e) {
        alert('Failed to copy text. Please manually select and copy.');
      }
    }
  };

  // Share using Web Share API
  const handleShare = async () => {
    const videoTitle = video?.title || 'Untitled Video';
    const shareData = {
      title: `Video Notes - ${videoTitle}`,
      text: getNotesText().substring(0, 500),
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        // User cancelled or share failed
        if (err.name !== 'AbortError') {
          console.error('Share failed:', err);
        }
      }
    } else {
      // Fallback: copy shareable link to clipboard
      try {
        await navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard! Share it with others.');
      } catch (err) {
        alert('Share this page URL: ' + window.location.href);
      }
    }
  };

  const hasAnyContent = transcript || summary || keyMoments.length > 0;

  if (loading) {
    return (
      <div className="pt-6 pb-12">
        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 xl:px-10">
          <div className="text-center py-12">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600 mx-auto"></div>
            <p className="text-gray-500 mt-2">Loading notes...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="pt-6 pb-12">
        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 xl:px-10">
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg flex items-center">
            <FiAlertCircle className="mr-2" />
            {error}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="pt-6 pb-12">
      <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 xl:px-10">
        {/* Header */}
        <div className="mb-6">
          <button
            onClick={() => navigate(`/videos/${videoId}`)}
            className="flex items-center text-gray-600 hover:text-gray-800 mb-4"
          >
            <FiArrowLeft className="mr-1" /> Back to Video
          </button>
          <div className="flex items-center gap-3 mb-2">
            <FiBookOpen className="text-3xl text-primary-600" />
            <div>
              <h1 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-gray-800">Video Notes</h1>
              {video && (
                <p className="text-sm sm:text-base text-gray-600 mt-1">{video.title}</p>
              )}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-3 mb-4 sm:mb-6 lg:mb-8">
          <button
            onClick={handleExportPDF}
            disabled={!hasAnyContent || exportingPdf}
            className="flex items-center px-4 py-2.5 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FiDownload className="mr-2" />
            {exportingPdf ? 'Exporting PDF...' : 'Export PDF'}
          </button>
          <button
            onClick={handleExportTXT}
            disabled={!hasAnyContent || exportingTxt}
            className="flex items-center px-4 py-2.5 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FiDownload className="mr-2" />
            {exportingTxt ? 'Exporting TXT...' : 'Export TXT'}
          </button>
          <button
            onClick={handleCopy}
            disabled={!hasAnyContent}
            className={`flex items-center px-4 py-2.5 rounded-lg transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed ${
              copied
                ? 'bg-green-600 text-white'
                : 'bg-primary-600 text-white hover:bg-primary-700'
            }`}
          >
            {copied ? (
              <><FiCheck className="mr-2" /> Copied!</>
            ) : (
              <><FiCopy className="mr-2" /> Copy Text</>
            )}
          </button>
          <button
            onClick={handleShare}
            disabled={!hasAnyContent}
            className="flex items-center px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FiShare2 className="mr-2" />
            Share
          </button>
        </div>

        {/* Notes Content */}
        {!hasAnyContent ? (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-12 text-center">
            <FiBookOpen className="text-6xl mx-auto mb-4 text-gray-300" />
            <h3 className="text-xl font-semibold text-gray-700 mb-2">No Notes Available</h3>
            <p className="text-gray-500 max-w-md mx-auto">
              Generate a transcript, summary, or key moments for this video to see your notes here.
            </p>
            <div className="mt-6 flex flex-wrap justify-center gap-3">
              <button
                onClick={() => navigate(`/videos/${videoId}/transcript`)}
                className="flex items-center px-4 py-2 bg-primary-50 text-primary-700 rounded-lg hover:bg-primary-100 transition-colors text-sm"
              >
                <FiFileText className="mr-2" />
                View Transcript
              </button>
              <button
                onClick={() => navigate(`/videos/${videoId}/summary`)}
                className="flex items-center px-4 py-2 bg-green-50 text-green-700 rounded-lg hover:bg-green-100 transition-colors text-sm"
              >
                <FiList className="mr-2" />
                View Summary
              </button>
              <button
                onClick={() => navigate(`/videos/${videoId}/key-moments`)}
                className="flex items-center px-4 py-2 bg-yellow-50 text-yellow-700 rounded-lg hover:bg-yellow-100 transition-colors text-sm"
              >
                <FiZap className="mr-2" />
                View Key Moments
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Summary Section */}
            {summary && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="bg-gradient-to-r from-blue-50 to-blue-100 px-6 py-4 border-b border-gray-200">
                  <h2 className="text-lg font-semibold text-gray-800 flex items-center">
                    <span className="mr-2 text-xl">📝</span> Summary
                  </h2>
                </div>
                <div className="p-4 sm:p-6 space-y-4">
                  {summary.short_summary && (
                    <div>
                      <h3 className="text-sm font-semibold text-gray-700 mb-2">Short Summary</h3>
                      <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{summary.short_summary}</p>
                    </div>
                  )}
                  {summary.detailed_summary && (
                    <div>
                      <h3 className="text-sm font-semibold text-gray-700 mb-2">Detailed Summary</h3>
                      <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{summary.detailed_summary}</p>
                    </div>
                  )}
                  {summary.model_used && (
                    <p className="text-xs text-gray-400 italic">
                      Generated using: {summary.model_used}
                    </p>
                  )}
                </div>
              </div>
            )}

            {/* Transcript Section */}
            {transcript?.transcript && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="bg-gradient-to-r from-green-50 to-green-100 px-6 py-4 border-b border-gray-200">
                  <h2 className="text-lg font-semibold text-gray-800 flex items-center">
                    <span className="mr-2 text-xl">🎙</span> Transcript
                  </h2>
                  {transcript.language && (
                    <span className="text-xs bg-white text-gray-600 px-2 py-0.5 rounded ml-3">
                      {transcript.language.toUpperCase()}
                    </span>
                  )}
                </div>
                <div className="p-4 sm:p-6">
                  <div className="prose prose-sm sm:prose lg:prose-lg max-w-none">
                    <p className="text-gray-700 whitespace-pre-wrap leading-relaxed text-sm">
                      {transcript.transcript}
                    </p>
                  </div>
                  {transcript.confidence && (
                    <p className="text-xs text-gray-400 mt-4">
                      Confidence: {transcript.confidence}%
                    </p>
                  )}
                </div>
              </div>
            )}

            {/* Key Moments Section */}
            {keyMoments.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="bg-gradient-to-r from-yellow-50 to-yellow-100 px-6 py-4 border-b border-gray-200">
                  <h2 className="text-lg font-semibold text-gray-800 flex items-center">
                    <span className="mr-2 text-xl">⏱</span> Key Moments
                  </h2>
                  <span className="text-xs text-gray-500 ml-3">
                    {keyMoments.length} moment{keyMoments.length !== 1 ? 's' : ''}
                  </span>
                </div>
                <div className="p-4 sm:p-6">
                  <div className="space-y-3">
                    {keyMoments.map((moment, index) => (
                      <div
                        key={moment.id || index}
                        className="flex items-start gap-4 p-3 bg-gray-50 rounded-lg border border-gray-100 hover:bg-yellow-50 hover:border-yellow-200 transition-all"
                      >
                        <div className="flex-shrink-0 bg-primary-100 text-primary-700 font-mono font-bold text-sm px-3 py-1.5 rounded-lg min-w-[70px] text-center">
                          {formatTimestamp(moment.start_time)}
                        </div>
                        <div className="flex-1 min-w-0">
                          <h4 className="font-medium text-gray-800 text-sm">{moment.title}</h4>
                          {moment.description && (
                            <p className="text-sm text-gray-600 mt-1 line-clamp-2">{moment.description}</p>
                          )}
                          {moment.confidence && (
                            <span className="inline-flex items-center mt-1 text-xs text-gray-400">
                              Confidence: {typeof moment.confidence === 'number' && moment.confidence <= 1
                                ? `${Math.round(moment.confidence * 100)}%`
                                : `${Math.round(moment.confidence)}%`
                              }
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Bottom Action Buttons*/}
            {/* <div className="flex flex-wrap gap-3 pt-2 pb-6">
              <button
                onClick={handleExportPDF}
                disabled={exportingPdf}
                className="flex items-center px-4 py-2.5 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors text-sm disabled:opacity-50"
              >
                <FiDownload className="mr-2" />
                {exportingPdf ? 'Exporting PDF...' : 'Export PDF'}
              </button>
              <button
                onClick={handleExportTXT}
                disabled={exportingTxt}
                className="flex items-center px-4 py-2.5 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors text-sm disabled:opacity-50"
              >
                <FiDownload className="mr-2" />
                {exportingTxt ? 'Exporting TXT...' : 'Export TXT'}
              </button>
              <button
                onClick={handleCopy}
                className={`flex items-center px-4 py-2.5 rounded-lg transition-colors text-sm ${
                  copied
                    ? 'bg-green-600 text-white'
                    : 'bg-primary-600 text-white hover:bg-primary-700'
                }`}
              >
                {copied ? (
                  <><FiCheck className="mr-2" /> Copied!</>
                ) : (
                  <><FiCopy className="mr-2" /> Copy Text</>
                )}
              </button>
              <button
                onClick={handleShare}
                className="flex items-center px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm"
              >
                <FiShare2 className="mr-2" />
                Share
              </button>
            </div> */}
        </div> 
        )}
      </div>
    </div>
  );
};

export default Notes;