# Generated by Django 6.0.6 on 2026-07-13 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMoment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timestamp_seconds', models.FloatField(default=0.0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_moments', to='videos.video')),
            ],
            options={
                'db_table': 'key_moments',
                'ordering': ['order', 'timestamp_seconds'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('ai_provider', models.CharField(default='groq', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='videos.video')),
            ],
            options={
                'verbose_name_plural': 'summaries',
                'db_table': 'summaries',
            },
        ),
    ]
