# Generated by Django 5.2.16 on 2026-08-15 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_keymoment_thumbnail'),
        ('videos', '0006_videoshare_bookmark_learninghistory_videoview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('study_notes', 'Study Notes'), ('quiz', 'Quiz'), ('flashcards', 'Flashcards'), ('lesson_plan', 'Lesson Plan')], default='study_notes', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='videos.video')),
            ],
            options={
                'db_table': 'learning_materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
