export const ROLES = {
  LEARNER: "LEARNER",
  EDUCATOR: "EDUCATOR",
  CONTENT_CREATOR: "CONTENT_CREATOR",
  ADMIN: "ADMIN",
};


export const FEATURE_ACCESS = {
  PROFILE: [
    ROLES.LEARNER,
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  ACTIVITY_HISTORY: [
    ROLES.LEARNER,
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  UPLOAD_VIDEO: [
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  VIDEOS: [
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  TRANSCRIPTS: [
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  SUMMARIES: [
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  KEY_MOMENTS: [
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],

  HIGHLIGHT_REPORT: [
    ROLES.EDUCATOR,
    ROLES.CONTENT_CREATOR,
    ROLES.ADMIN,
  ],
};


export const hasFeatureAccess = (role, feature) => {
  return FEATURE_ACCESS[feature]?.includes(role);
};