# Generated by Django 5.2.16 on 2026-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_drop_clips_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
