# Generated by Django 5.2.16 on 2026-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
