# Generated by Django 5.2.16 on 2026-07-16 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_source_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='videos.video')),
            ],
            options={
                'db_table': 'video_translations',
                'unique_together': {('video', 'language')},
            },
        ),
    ]
