# Generated by Django 5.2.16 on 2026-08-15 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videotranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='videos.video')),
            ],
            options={
                'db_table': 'video_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='videos.video')),
            ],
            options={
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video', 'timestamp_seconds')},
            },
        ),
        migrations.CreateModel(
            name='LearningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_position_seconds', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_history', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_history', to='videos.video')),
            ],
            options={
                'db_table': 'learning_history',
                'ordering': ['-last_viewed_at'],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='videos.video')),
            ],
            options={
                'db_table': 'video_views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', '-created_at'], name='video_views_video_i_1f7f7e_idx'), models.Index(fields=['user', '-created_at'], name='video_views_user_id_d42f94_idx')],
            },
        ),
    ]
