import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import {
  FiBookmark,
  FiCopy,
  FiCpu,
  FiDownload,
  FiShare2,
} from "react-icons/fi";
import { useEffect, useState } from "react";
import { useWorkspace } from "../../context/WorkspaceContext";
import { EmptyState } from "../../components/EmptyState";
import { VideoSelect } from "../../components/VideoSelect";
import { useToast } from "../../context/ToastContext";
import { useAuth } from "../../context/AuthContext";

export const Route = createFileRoute("/_authenticated/summary")({
  head: () => ({
    meta: [
      { title: "AI Summary — ClipMind AI" },
      {
        name: "description",
        content:
          "Structured AI summary with short summary, detailed summary, abstract, key findings, topics and follow-up actions for your processed recording.",
      },
      {
        property: "og:title",
        content: "AI Summary — ClipMind AI",
      },
      {
        property: "og:description",
        content:
          "Short and detailed summaries, content abstraction, key findings and topic labels generated from your transcript.",
      },
    ],
  }),
  component: SummaryPage,
});

function SummaryPage() {
  const { active } = useWorkspace();
  const { toast } = useToast();
  const { user } = useAuth();

  const [bookmarked, setBookmarked] = useState(false);

  useEffect(() => {
    if (!active || !user) {
      setBookmarked(false);
      return;
    }

    try {
      const key = `clipmind_bookmarked_summaries:${user.id}`;
      const raw = localStorage.getItem(key);
      const ids: string[] = raw ? JSON.parse(raw) : [];

      setBookmarked(ids.includes(active.id));
    } catch {
      setBookmarked(false);
    }
  }, [active?.id, user?.id]);

  if (!active?.summary) {
    return (
      <EmptyState
        icon={<FiCpu />}
        title="No summary generated yet"
        description="Upload and process a recording to generate its short summary, detailed summary, abstract, key findings and topic labels."
      />
    );
  }

  const s = active.summary;

  /*
   * Copy text to clipboard
   */
  const copyText = async (
    text: string,
    message: string,
  ) => {
    try {
      await navigator.clipboard.writeText(text);
      toast(message, "success");
    } catch {
      toast("Unable to copy text", "error");
    }
  };

  /*
   * Bookmark / unbookmark summary
   */
  const toggleBookmark = () => {
    if (!user) return;

    try {
      const key = `clipmind_bookmarked_summaries:${user.id}`;
      const raw = localStorage.getItem(key);
      const ids: string[] = raw ? JSON.parse(raw) : [];

      let nextIds: string[];

      if (ids.includes(active.id)) {
        nextIds = ids.filter((id) => id !== active.id);
        setBookmarked(false);
        toast("Summary removed from bookmarks", "success");
      } else {
        nextIds = [...ids, active.id];
        setBookmarked(true);
        toast("Summary bookmarked", "success");
      }

      localStorage.setItem(key, JSON.stringify(nextIds));
    } catch {
      toast("Unable to update bookmark", "error");
    }
  };

  /*
   * Build a complete downloadable summary.
   *
   * This is intentionally a plain-text download so it works
   * without requiring any additional PDF/document library.
   */
  const downloadSummary = () => {
    try {
      const text = [
        "CLIPMIND AI — CONTENT SUMMARY",
        "================================",
        "",
        `Title: ${active.title}`,
        `Duration: ${active.duration}`,
        "",
        "SHORT SUMMARY",
        "-------------",
        s.shortSummary,
        "",
        "ABSTRACT",
        "--------",
        s.abstract,
        "",
        "DETAILED SUMMARY",
        "----------------",
        s.detailedSummary,
        "",
        "KEY FINDINGS",
        "------------",
        ...s.bullets.map(
          (bullet, index) => `${index + 1}. ${bullet}`,
        ),
        "",
        "TOPICS",
        "------",
        ...s.topics.map((topic) => `• ${topic}`),
        "",
        "FOLLOW-UP ACTIONS",
        "-----------------",
        ...s.actionItems.map((action) => `• ${action}`),
        "",
        "SUMMARY METRICS",
        "---------------",
        `Transcribed Words: ${s.wordCount}`,
        `Compression: ${s.compression}%`,
        `Topics Detected: ${s.topics.length}`,
        "",
        "Generated by ClipMind AI",
      ].join("\n");

      const blob = new Blob([text], {
        type: "text/plain;charset=utf-8",
      });

      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");

      anchor.href = url;
      anchor.download = `${active.title
        .replace(/[^a-z0-9]/gi, "_")
        .replace(/_+/g, "_")}_Summary.txt`;

      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);

      URL.revokeObjectURL(url);

      toast("Summary downloaded", "success");
    } catch {
      toast("Unable to download summary", "error");
    }
  };

  /*
   * Share summary.
   *
   * Content Creator gets a generic Share Summary action rather
   * than the Educator-specific "Share with Students" action.
   */
  const shareSummary = async () => {
    const text = [
      `ClipMind AI — ${active.title}`,
      "",
      "Short Summary:",
      s.shortSummary,
      "",
      "Key Findings:",
      ...s.bullets.map(
        (bullet, index) => `${index + 1}. ${bullet}`,
      ),
      "",
      `Topics: ${s.topics.join(", ")}`,
    ].join("\n");

    try {
      if (navigator.share) {
        await navigator.share({
          title: `ClipMind AI — ${active.title}`,
          text,
        });

        toast("Summary shared", "success");
      } else {
        await navigator.clipboard.writeText(text);

        toast(
          "Summary copied for sharing",
          "success",
        );
      }
    } catch (error) {
      // Browser share was cancelled by the user.
      if (
        error instanceof DOMException &&
        error.name === "AbortError"
      ) {
        return;
      }

      toast("Unable to share summary", "error");
    }
  };

  return (
    <div className="mx-auto max-w-4xl space-y-5">

      {/* =========================================================
          HEADER
      ========================================================= */}
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl">
            AI Summary
          </h1>

          <p className="mt-1 text-sm text-muted-foreground">
            {active.title} · {active.duration}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">

          <VideoSelect />

          {/* Share Summary */}
          <button
            onClick={shareSummary}
            className="inline-flex h-10 items-center gap-2 rounded-xl border border-border bg-card px-3 text-sm text-muted-foreground hover:bg-muted hover:text-foreground"
          >
            <FiShare2 />
            Share Summary
          </button>

          {/* Bookmark Summary */}
          <button
            onClick={toggleBookmark}
            className={`inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-sm transition-colors ${
              bookmarked
                ? "border-primary bg-primary/10 text-primary"
                : "border-border bg-card text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <FiBookmark />

            {bookmarked
              ? "Bookmarked"
              : "Bookmark Summary"}
          </button>

          {/* Download Summary */}
          <button
            onClick={downloadSummary}
            className="inline-flex h-10 items-center gap-2 rounded-xl border border-border bg-card px-3 text-sm text-muted-foreground hover:bg-muted hover:text-foreground"
          >
            <FiDownload />
            Download
          </button>

        </div>
      </div>

      {/* =========================================================
          SUMMARY METRICS
      ========================================================= */}
      <div className="grid gap-3 sm:grid-cols-3">
        {[
          {
            label: "Transcribed words",
            value: s.wordCount,
          },
          {
            label: "Compression",
            value: `${s.compression}%`,
          },
          {
            label: "Topics detected",
            value: s.topics.length,
          },
        ].map((metric) => (
          <div
            key={metric.label}
            className="rounded-2xl border border-border bg-card p-4"
          >
            <div className="text-[11px] uppercase tracking-widest text-muted-foreground">
              {metric.label}
            </div>

            <div className="mt-1.5 font-display text-xl">
              {metric.value}
            </div>
          </div>
        ))}
      </div>

      {/* =========================================================
          SHORT SUMMARY
      ========================================================= */}
      <motion.section
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-2xl border border-border bg-card p-6"
      >
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="font-display text-lg">
              Short Summary
            </h2>

            <p className="mt-1 text-xs text-muted-foreground">
              A concise overview of the recording.
            </p>
          </div>

          <button
            onClick={() =>
              copyText(
                s.shortSummary,
                "Short summary copied",
              )
            }
            className="inline-flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:text-foreground"
          >
            <FiCopy />
            Copy
          </button>
        </div>

        <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
          {s.shortSummary}
        </p>
      </motion.section>

      {/* =========================================================
          ABSTRACT
      ========================================================= */}
      <motion.section
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.05 }}
        className="rounded-2xl border border-border bg-card p-6"
      >
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="font-display text-lg">
              Abstract
            </h2>

            <p className="mt-1 text-xs text-muted-foreground">
              High-level content abstraction.
            </p>
          </div>

          <button
            onClick={() =>
              copyText(
                s.abstract,
                "Abstract copied",
              )
            }
            className="inline-flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:text-foreground"
          >
            <FiCopy />
            Copy
          </button>
        </div>

        <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
          {s.abstract}
        </p>
      </motion.section>

      {/* =========================================================
          DETAILED SUMMARY
      ========================================================= */}
      <motion.section
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="rounded-2xl border border-border bg-card p-6"
      >
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="font-display text-lg">
              Detailed Summary
            </h2>

            <p className="mt-1 text-xs text-muted-foreground">
              A more comprehensive summary of the recorded discussion.
            </p>
          </div>

          <button
            onClick={() =>
              copyText(
                s.detailedSummary,
                "Detailed summary copied",
              )
            }
            className="inline-flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:text-foreground"
          >
            <FiCopy />
            Copy
          </button>
        </div>

        <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
          {s.detailedSummary}
        </p>
      </motion.section>

      {/* =========================================================
          KEY FINDINGS
      ========================================================= */}
      <section className="rounded-2xl border border-border bg-card p-6">
        <h2 className="font-display text-lg">
          Key Findings
        </h2>

        <ul className="mt-3 space-y-2.5">
          {s.bullets.map((bullet, index) => (
            <li
              key={index}
              className="flex gap-3 text-sm"
            >
              <span className="font-mono-num text-xs text-primary">
                {String(index + 1).padStart(2, "0")}
              </span>

              <span className="text-muted-foreground">
                {bullet}
              </span>
            </li>
          ))}
        </ul>
      </section>

      {/* =========================================================
          TOPICS + FOLLOW-UP ACTIONS
      ========================================================= */}
      <div className="grid gap-3 md:grid-cols-2">

        {/* Topics */}
        <section className="rounded-2xl border border-border bg-card p-6">
          <h2 className="font-display text-lg">
            Topics
          </h2>

          <div className="mt-3 flex flex-wrap gap-2">
            {s.topics.map((topic) => (
              <span
                key={topic}
                className="rounded-lg border border-border bg-muted px-2.5 py-1 text-xs text-muted-foreground"
              >
                {topic}
              </span>
            ))}
          </div>
        </section>

        {/* Follow-up Actions */}
        <section className="rounded-2xl border border-border bg-card p-6">
          <h2 className="font-display text-lg">
            Follow-up Actions
          </h2>

          <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
            {s.actionItems.map((action) => (
              <li key={action}>
                · {action}
              </li>
            ))}
          </ul>
        </section>

      </div>
    </div>
  );
}