/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMomentsRouteImport } from './routes/_authenticated/moments'
import { Route as AuthenticatedPlatformActivityRouteImport } from './routes/_authenticated/platform-activity'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform-settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as AuthenticatedSystemAnalyticsRouteImport } from './routes/_authenticated/system-analytics'
import { Route as AuthenticatedTranscriptRouteImport } from './routes/_authenticated/transcript'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMomentsRoute = AuthenticatedMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlatformActivityRoute =
  AuthenticatedPlatformActivityRouteImport.update({
    id: '/platform-activity',
    path: '/platform-activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemAnalyticsRoute =
  AuthenticatedSystemAnalyticsRouteImport.update({
    id: '/system-analytics',
    path: '/system-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTranscriptRoute = AuthenticatedTranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/platform-activity': typeof AuthenticatedPlatformActivityRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/system-analytics': typeof AuthenticatedSystemAnalyticsRoute
  '/transcript': typeof AuthenticatedTranscriptRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/platform-activity': typeof AuthenticatedPlatformActivityRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/system-analytics': typeof AuthenticatedSystemAnalyticsRoute
  '/transcript': typeof AuthenticatedTranscriptRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/moments': typeof AuthenticatedMomentsRoute
  '/_authenticated/platform-activity': typeof AuthenticatedPlatformActivityRoute
  '/_authenticated/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/system-analytics': typeof AuthenticatedSystemAnalyticsRoute
  '/_authenticated/transcript': typeof AuthenticatedTranscriptRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/activity'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/moments'
    | '/platform-activity'
    | '/platform-settings'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/system-analytics'
    | '/transcript'
    | '/upload'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/activity'
    | '/analytics'
    | '/dashboard'
    | '/history'
    | '/moments'
    | '/platform-activity'
    | '/platform-settings'
    | '/profile'
    | '/settings'
    | '/summary'
    | '/system-analytics'
    | '/transcript'
    | '/upload'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authenticated/activity'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/moments'
    | '/_authenticated/platform-activity'
    | '/_authenticated/platform-settings'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/summary'
    | '/_authenticated/system-analytics'
    | '/_authenticated/transcript'
    | '/_authenticated/upload'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moments': {
      id: '/_authenticated/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AuthenticatedMomentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform-activity': {
      id: '/_authenticated/platform-activity'
      path: '/platform-activity'
      fullPath: '/platform-activity'
      preLoaderRoute: typeof AuthenticatedPlatformActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform-settings': {
      id: '/_authenticated/platform-settings'
      path: '/platform-settings'
      fullPath: '/platform-settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system-analytics': {
      id: '/_authenticated/system-analytics'
      path: '/system-analytics'
      fullPath: '/system-analytics'
      preLoaderRoute: typeof AuthenticatedSystemAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transcript': {
      id: '/_authenticated/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof AuthenticatedTranscriptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMomentsRoute: typeof AuthenticatedMomentsRoute
  AuthenticatedPlatformActivityRoute: typeof AuthenticatedPlatformActivityRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedSystemAnalyticsRoute: typeof AuthenticatedSystemAnalyticsRoute
  AuthenticatedTranscriptRoute: typeof AuthenticatedTranscriptRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMomentsRoute: AuthenticatedMomentsRoute,
  AuthenticatedPlatformActivityRoute: AuthenticatedPlatformActivityRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedSystemAnalyticsRoute: AuthenticatedSystemAnalyticsRoute,
  AuthenticatedTranscriptRoute: AuthenticatedTranscriptRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
