"use client";

import { useEffect, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";

import {
  getSummary,
  getVideo,
} from "@/services/video";

import jsPDF from "jspdf";

import VideoPlayer from "@/components/Dashboard/VideoPlayer";

import { createBookmark } from "@/services/bookmark";

import {
  getMyClassrooms,
} from "@/services/classroom";

import {
  shareSummary,
} from "@/services/summaryShare";

import { useAuth } from "@/context/AuthContext";

export default function SummaryPage() {
  const searchParams = useSearchParams();
  const router = useRouter();

  const [summary, setSummary] = useState("Loading...");
  const [shortSummary, setShortSummary] = useState("Loading...");

  const [videoName, setVideoName] = useState("");
  const [videoFilename, setVideoFilename] = useState("");

  const [videoId, setVideoId] = useState<number | null>(null);

  const { user } = useAuth();

  const [classrooms, setClassrooms] = useState<any[]>([]);

  const [selectedClassroom, setSelectedClassroom] =
    useState<number | null>(null);

  const [sharing, setSharing] = useState(false);
  const [shareMessage, setShareMessage] = useState("");

  useEffect(() => {
    const id = searchParams.get("videoId");

    if (!id) {
      setSummary("No video selected.");
      setShortSummary("");
      return;
    }

    const numericId = Number(id);

    if (isNaN(numericId)) {
      setSummary("Invalid video ID.");
      setShortSummary("");
      return;
    }

    setVideoId(numericId);

    const loadSummary = async () => {
      try {
        console.log(
          "Loading summary for video:",
          numericId
        );

        // Get video details for player
        const video = await getVideo(numericId);

        setVideoName(
          video.original_filename ||
            `Video ${numericId}`
        );

        setVideoFilename(
          video.filename || ""
        );

        // Get summary
        const data = await getSummary(numericId);

        console.log("Summary API:", data);

        setSummary(
          data.summary ||
            "Summary not available."
        );

        setShortSummary(
          data.short_summary ||
            "Short summary not available."
        );
      } catch (error) {
        console.error(
          "Summary Error:",
          error
        );

        setSummary(
          "Failed to load summary."
        );

        setShortSummary(
          "Failed to load short summary."
        );
      }
    };

    loadSummary();
  }, [searchParams]);

  useEffect(() => {
    if (user?.role !== "educator") return;

    const loadClassrooms = async () => {
      try {
        const data = await getMyClassrooms();

        console.log(
          "MY CLASSROOMS:",
          data
        );

        setClassrooms(data);
      } catch (error) {
        console.error(
          "Failed to load classrooms:",
          error
        );
      }
    };

    loadClassrooms();
  }, [user]);

  const downloadSummary = () => {
    const doc = new jsPDF();

    let y = 20;

    doc.setFontSize(20);

    doc.text(
      "ClipMind AI Summary Report",
      20,
      y
    );

    y += 15;

    doc.setFontSize(12);

    doc.text(
      `Video Name: ${videoName}`,
      20,
      y
    );

    y += 10;

    doc.text(
      `Generated On: ${new Date().toLocaleString()}`,
      20,
      y
    );

    y += 15;

    doc.setFontSize(16);

    doc.text(
      "AI Summary",
      20,
      y
    );

    y += 10;

    doc.setFontSize(12);

    const summaryLines =
      doc.splitTextToSize(
        summary,
        170
      );

    doc.text(
      summaryLines,
      20,
      y
    );

    y +=
      summaryLines.length * 7 +
      15;

    doc.setFontSize(16);

    doc.text(
      "Short Summary",
      20,
      y
    );

    y += 10;

    doc.setFontSize(12);

    const shortSummaryLines =
      doc.splitTextToSize(
        shortSummary,
        170
      );

    doc.text(
      shortSummaryLines,
      20,
      y
    );

    doc.setFontSize(10);

    doc.text(
      "Generated by ClipMind AI",
      20,
      285
    );

    doc.save(
      `${videoName || "summary"}_Summary.pdf`
    );
  };

  const handleShareSummary = async () => {
    if (!videoId || !selectedClassroom) {
      setShareMessage(
        "Please select a classroom first."
      );
      return;
    }

    try {
      setSharing(true);
      setShareMessage("");

      await shareSummary(
        videoId,
        selectedClassroom
      );

      setShareMessage(
        "✅ Summary shared successfully!"
      );
    } catch (error: any) {
      console.error(
        "Share summary error:",
        error
      );

      const message =
        error?.response?.data?.detail ||
        "Failed to share summary.";

      setShareMessage(
        `❌ ${message}`
      );
    } finally {
      setSharing(false);
    }
  };

  const goToKeyMoments = () => {
    if (!videoId) return;

    router.push(
      `/dashboard/key-moments?videoId=${videoId}`
    );
  };

  const goToKeywords = () => {
    if (!videoId) return;

    router.push(
      `/dashboard/keywords?videoId=${videoId}`
    );
  };

  const bookmarkSummary = async () => {
    if (!videoId || !summary) return;

    try {
      await createBookmark({
        video_id: videoId,
        bookmark_type: "summary",
        content: summary,
      });

      alert(
        "🔖 Summary bookmarked successfully!"
      );
    } catch (error) {
      console.error(
        "Bookmark summary error:",
        error
      );

      alert(
        "❌ Failed to bookmark summary."
      );
    }
  };

  return (
    <div className="p-8">

      <h1 className="text-3xl font-bold mb-6">
        📝 AI Summary
      </h1>

      {/* Video Player */}

      {videoFilename && (
        <VideoPlayer
          filename={videoFilename}
          videoName={videoName}
        />
      )}

      <div className="bg-white rounded-xl shadow-lg p-6">

        <h2 className="font-semibold text-lg mb-4 text-black">
          {videoName}
        </h2>

        {/* Detailed Summary */}

        <div className="mb-8">

          <h2 className="text-2xl font-semibold text-black mb-4">
            📄 Detailed Summary
          </h2>

          <div className="whitespace-pre-wrap leading-8 text-black">
            {summary}
          </div>

         {user?.role === "learner" && (
  <button
    onClick={bookmarkSummary}
    disabled={!videoId || summary === "Loading..."}
    className="mt-4 bg-yellow-500 hover:bg-yellow-600 disabled:bg-gray-400 text-white px-4 py-2 rounded-lg shadow transition"
  >
    🔖 Bookmark Summary
  </button>
)}

        </div>

        {/* Short Summary */}

        <div className="mb-8">

          <h2 className="text-2xl font-semibold text-black mb-4">
            ⚡ Short Summary
          </h2>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-black leading-7">
            {shortSummary}
          </div>

        </div>

        {/* Share Summary */}

        <div className="mt-6 flex justify-between items-center gap-4 flex-wrap">

          {user?.role === "educator" && (
            <div className="mb-8 border border-purple-200 rounded-xl p-5 bg-purple-50">

              <h2 className="text-2xl font-semibold text-black mb-4">
                📤 Share Summary
              </h2>

              <p className="text-gray-700 mb-4">
                Share this AI-generated summary with one of your classrooms.
              </p>

              <div className="flex gap-3 flex-wrap items-center">

                <select
                  value={
                    selectedClassroom ?? ""
                  }
                  onChange={(e) =>
                    setSelectedClassroom(
                      e.target.value
                        ? Number(
                            e.target.value
                          )
                        : null
                    )
                  }
                  className="px-4 py-3 border border-gray-300 rounded-lg text-black bg-white min-w-[250px]"
                >
                  <option value="">
                    Select a classroom
                  </option>

                  {classrooms.map(
                    (classroom) => (
                      <option
                        key={classroom.id}
                        value={classroom.id}
                      >
                        {classroom.name} (
                        {classroom.code})
                      </option>
                    )
                  )}
                </select>

                <button
                  onClick={
                    handleShareSummary
                  }
                  disabled={
                    !videoId ||
                    !selectedClassroom ||
                    sharing ||
                    summary === "Loading..."
                  }
                  className="bg-purple-600 hover:bg-purple-700 disabled:bg-gray-400 text-white px-5 py-3 rounded-lg shadow transition"
                >
                  {sharing
                    ? "Sharing..."
                    : "📤 Share Summary"}
                </button>

              </div>

              {shareMessage && (
                <p className="mt-3 text-sm font-semibold text-gray-700">
                  {shareMessage}
                </p>
              )}

            </div>
          )}

          {/* Navigation Buttons */}

          <div className="flex gap-3 flex-wrap">

            <button
              onClick={goToKeywords}
              disabled={!videoId}
              className="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white px-4 py-2 rounded-lg shadow transition"
            >
              🏷 View Keywords →
            </button>

            <button
              onClick={goToKeyMoments}
              disabled={!videoId}
              className="bg-yellow-500 hover:bg-yellow-600 disabled:bg-gray-400 text-white px-4 py-2 rounded-lg shadow transition"
            >
              ⭐ View Key Moments →
            </button>

          </div>

          {/* Download */}

          <button
            onClick={downloadSummary}
            className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg shadow transition"
          >
            ⬇ Download Summary
          </button>

        </div>

      </div>

    </div>
  );
}